# Generated by Django 5.0.6 on 2024-07-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='DemoFiles')),
                ('image', models.FileField(blank=True, null=True, upload_to='DemoFiles')),
            ],
        ),
    ]
